"""empty message

Revision ID: 2442abe1b0cb
Revises: d655eb1736e0
Create Date: 2021-03-17 20:30:30.195262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2442abe1b0cb'
down_revision = 'd655eb1736e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('propertyTitle', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'propertyTitle')
    # ### end Alembic commands ###
