"""empty message

Revision ID: 4c601c83b062
Revises: 
Create Date: 2021-03-17 16:29:16.624244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c601c83b062'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('propertyTitle', sa.String(length=30), nullable=False),
    sa.Column('propertyDescription', sa.String(length=355), nullable=False),
    sa.Column('propertyBathrooms', sa.Integer(), nullable=False),
    sa.Column('propertyBedrooms', sa.Integer(), nullable=False),
    sa.Column('propertyType', sa.String(length=30), nullable=False),
    sa.Column('propertyPhoto', sa.String(length=255), nullable=False),
    sa.Column('propertyPrice', sa.Float(precision=2), nullable=False),
    sa.Column('propertyLocation', sa.String(length=355), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###
