"""empty message

Revision ID: d655eb1736e0
Revises: 4c601c83b062
Create Date: 2021-03-17 20:30:01.477945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd655eb1736e0'
down_revision = '4c601c83b062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'propertyTitle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('propertyTitle', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
